import React, { useEffect, useState } from "react";
import { useParams } from "react-router-dom";

/* File updated/generated by chatgpt 4o generated code */


function BookEvent() {
  const { id } = useParams();
  const [event, setEvent] = useState(null);

  useEffect(() => {
    const getEvent = async () => {
      try {
        const res = await fetch(
          `https://eventservicenew-dxbphqh2cegwf7gq.swedencentral-01.azurewebsites.net/api/Events/${id}`
        );
        if (res.ok) {
          const data = await res.json();
          setEvent(data.result);
        } else {
          console.error("Failed to fetch event");
        }
      } catch (err) {
        console.error("Error fetching event", err);
      }
    };

    getEvent();
  }, [id]);

  if (!event) return <p>Loading...</p>;

  return (
    <div>
      <h1>Book Event - {event.title}</h1>
      <p>{event.description}</p>
    </div>
  );
}

export default BookEvent;

/* File updated/generated by chatgpt 4o generated code */