import React, { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';

/* Code generated by chatgpt 4o based on the eventcard file */
const EventDetails = () => {
  const { id } = useParams();
  const [event, setEvent] = useState(null);

  useEffect(() => {
    const getEvent = async () => {
      const res = await fetch(`https://localhost:7283/api/events/${id}`);
      if (res.ok) {
        const data = await res.json();
        setEvent(data);
      }
    };

    getEvent();
  }, [id]);

  if (!event) return <p>Loading...</p>;

  return (
    <div className="event-details-container">
        <div className="event-details-page">
        <div className="event-card large">
            {/* HEADER */}
            <div className="card-header">
            <div className="image-wrapper">
                <img
                src={event.image ?? "/placeholder.svg"}
                alt="event img"
                className={event.image ? "" : "placeholder-img"}
                />
                <div className="image-overlay">
                <span className="badge category">{event.category || "No category"}</span>
                <span className={`badge status ${!event.status ? "missing" : ""}`}>
                    <span className="dot"></span>
                    {event.status || "No status"}
                </span>
                </div>
            </div>
            </div>

            {/* BODY */}
            <div className="card-body">
            <p className="event-date-time">{event.date ?? "No date"}</p>
            <h2 className="event-title">{event.name ?? "Untitled Event"}</h2>
            <p className="event-location">
                <i className="fa-solid fa-location-dot"></i>
                {event.location || "No location"}
            </p>
            <p className="event-description">
                {event.description || "No description provided."}
            </p>
            </div>

            {/* FOOTER */}
            <div className="card-footer">
            <div className="event-progress">
                <div className="progress-bar">
                <div className="progress" style={{ width: "65%" }}></div>
                </div>
                <span className="progress-label"><img src="/chart.svg" alt="chart" />65%</span>
            </div>
            <div className="event-price">
                {event.price ? `$${event.price}` : "No price"}
            </div>
            </div>
        </div>
        </div>
    </div>
  );
};

export default EventDetails;

/* Code generated by chatgpt 4o based on the eventcard file */