import React, { useEffect, useState } from "react";
import { useParams } from "react-router-dom";

/* Code generated by chatgpt 4o based on the eventcard file */

const EventDetails = () => {
  const { id } = useParams();
  const [event, setEvent] = useState(null);

  useEffect(() => {
    const getEvent = async () => {
      const res = await fetch(`https://localhost:7283/api/events/${id}`);
      if (res.ok) {
        const data = await res.json();
        setEvent(data);
      }
    };

    getEvent();
  }, [id]);

  if (!event) return <p>Loading...</p>;

  return (
    <div className="event-details-container">
      <div className="event-details-page">
        <div className="event-card large event-card-details">
          {/* HEADER */}
          <div className="card-header">
            <img src={event.image ?? "/placeholder.svg"} alt="event" />
            <div className="image-overlay">
              <span className="badge category">
                {event.category || "Music"}
              </span>
              <span
                className={`badge status ${!event.status ? "missing" : ""}`}
              >
                <span className="dot"></span>
                {event.status || "Active"}
              </span>
            </div>
          </div>

          {/* BODY */}
          <div className="card-body">
            <div className="event-title-bookmark-share-wrapper">
              <h2 className="event-title">
                {event.name ?? "Echo Beats Festival"}
              </h2>
              <div className="button-wrapper">
                <button className="fa-button"><i className="fa-regular fa-bookmark fa-button-styling"></i></button>
                <button className="fa-button"><i className="fa-regular fa-share-nodes fa-button-styling"></i></button>
              </div>
            </div>
            <p className="event-date-time">
              {event.date ?? "May 20, 2029 — 6:00 PM"}
            </p>
            <div className="event-location-ticket-info">
              <p className="event-location">
                <i className="fa-solid fa-location-dot"></i>
                {event.location || "Sunset Park, Los Angeles, CA"}
                <span className="show-map">Show Map</span>
              </p>
              <div className="tickets-and-price-wrapper">
                <div className="tickets">
                  <p>Tickets Sold</p>
                  <strong>{event.ticketsSold ?? 21000}</strong>/
                  {event.ticketLimit ?? 30000}
                </div>
                <div className="price">
                  <p>Starts From</p>
                  {event.price
                    ? `$${event.price}`
                    : "Starts from $60"}
                </div>
              </div>
            </div>
          </div>

          {/* FOOTER */}
          <div className="card-footer">
            {/* DESCRIPTION */}
            <div className="event-description">
              <p className="about-title">About Event</p>
              <p>{event.description ?? "Description coming soon."}</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default EventDetails;

/* Code generated by chatgpt 4o based on the eventcard file */
