import React, { useEffect, useState } from "react";
import { useParams, Link } from "react-router-dom";

/* Code generated by chatgpt 4o based on the eventcard file */

const EventDetails = () => {
  const { id } = useParams();
  const [event, setEvent] = useState(null);

  useEffect(() => {
    const getEvent = async () => {
      try {
        const res = await fetch(
          `https://eventservicenew-dxbphqh2cegwf7gq.swedencentral-01.azurewebsites.net/api/Events/${id}`
        );
        if (res.ok) {
          const data = await res.json();
          setEvent(data.result);
        } else {
          console.error("Failed to fetch event");
        }
      } catch (err) {
        console.error("Error fetching event", err);
      }
    };

    getEvent();
  }, [id]);

  if (!event) return <p>Loading...</p>;

  // Utility fallback for image
  const image =
    event.image && event.image.trim() !== ""
      ? event.image
      : "/placeholder.svg";

  const name = event.title ?? "Echo Beats Festival PH";
  const date = event.eventDate
    ? new Date(event.eventDate).toLocaleString()
    : "May 20, 2029 — 6:00 PM";
  const location = event.location ?? "Sunset Park, Los Angeles, CA PH";
  const status = event.status ?? "Active";
  const category = event.category ?? "Music";
  const description = event.description ?? "Description coming soon. PH";

  const hasPackages =
    Array.isArray(event.packages) && event.packages.length > 0;
  const firstPackage = hasPackages ? event.packages[0] : null;

  const ticketsSold = firstPackage?.ticketsSold ?? 21000;
  const ticketLimit = firstPackage?.ticketLimit ?? 30000;
  const price = firstPackage?.price ? `$${firstPackage.price}` : "$60";

  return (
    <div className="event-details-container">
      <div className="event-details-page">
        <div className="event-card large event-card-details">
          {/* HEADER */}
          <div className="card-header">
            <img src={image} alt="event" />
            <div className="image-overlay">
              <span className="badge category">{category}</span>
              <span className={`badge status ${!status ? "missing" : ""}`}>
                <span className="dot"></span>
                {status}
              </span>
            </div>
          </div>

          {/* BODY */}
          <div className="card-body">
            <div className="event-title-bookmark-share-wrapper">
              <h2 className="event-title">{name}</h2>
              <div className="button-wrapper">
                <button className="fa-button">
                  <i className="fa-regular fa-bookmark fa-button-styling"></i>
                </button>
                <button className="fa-button">
                  <i className="fa-regular fa-share-nodes fa-button-styling"></i>
                </button>
              </div>
            </div>
            <div className="event-location-ticket-info">
              <div className="date-time-location-wrapper">
                <div className="event-date-time-div">
                  <p className="event-date-time">{date}</p>
                </div>
                <div className="event-location-div">
                  <p className="event-location">
                    <i className="fa-solid fa-location-dot"></i>
                    {location}
                  </p>
                </div>
              </div>
              <div className="tickets-and-price-wrapper">
                <div className="tickets">
                  <p className="tickets-sold">Tickets Sold</p>
                  <div className="tickets-sold-wrapper">
                    <strong className="tickets-sold-amount">
                      {ticketsSold}
                    </strong>
                    <p className="tickets-limit">/{ticketLimit}</p>
                  </div>
                </div>
                <div className="price">
                  <p className="starts-from">Starts From</p>
                  <div className="starts-from-wrapper">
                    <strong className="starts-from-price">{price}</strong>
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* FOOTER */}
          <div className="card-footer">
            <div className="event-description">
              <p className="about-title">About Event</p>
              <p>{description}</p>
            </div>
          </div>
        </div>
      </div>
      <div className="booking-link">
        <Link to={`/events/bookings/${id}`}>Book Event</Link>
      </div>
    </div>
  );
};

export default EventDetails;

/* Code generated by chatgpt 4o based on the eventcard file */
