/* File updated to react compatible with code generated by chatgpt 4o */

import React from 'react'

const SignUp = () => {
  return (
    <section id="signup">
      <div className="card">

        <div className="card-header">
          <h1>Sign Up</h1>
        </div>

        <div className="card-body">
          <form method="post" noValidate>

            <div className="form-group">
              <label className="form-label" htmlFor="firstName">First Name</label>
              <input className="form-input" type="text" id="firstName" name="firstName" />
            </div>

            <div className="form-group">
              <label className="form-label" htmlFor="lastName">Last Name</label>
              <input className="form-input" type="text" id="lastName" name="lastName" />
            </div>

            <div className="form-group">
              <label className="form-label" htmlFor="email">Email</label>
              <input className="form-input" type="email" id="email" name="email" />
            </div>

            <div className="form-group">
              <label className="form-label" htmlFor="password">Password</label>
              <input className="form-input" type="password" id="password" name="password" />
            </div>

            <div className="form-group">
              <label className="form-label" htmlFor="confirmPassword">Confirm Password</label>
              <input className="form-input" type="password" id="confirmPassword" name="confirmPassword" />
            </div>

            <div className="form-checkbox-group">
              <label className="form-checkbox">
                <input type="checkbox" id="terms" className="form-checkbox-input" name="terms" />
                <span className="form-checkbox-box"></span>
              </label>
              <label htmlFor="terms" className="form-label">
                I Accept <a href="#">Terms and Conditions</a>
              </label>
            </div>

            <button type="submit" className="btn">Create Account</button>
          </form>
        </div>

        <div className="card-footer">
          Already have an account? <a href="/signin">Log in</a>
        </div>

      </div>
    </section>
  )
}

export default SignUp

/* File updated to react compatible with code generated by chatgpt 4o */