import React from "react";

/* EventCard formatted to JSX from Razor by help of ChatGpt4o, code generated by ChatGpt 4o and updateded structure to match eventcard from figma */

const EventCard = ({ event }) => {
  return (
    <div className="event-card" data-event-id={event.Id}>
      {/* HEADER: Image with category/status badges */}
      <div className="card-header">
        <div className="image-wrapper">
          <img
            src={event.image ?? "/placeholder.svg"}
            alt="event img"
            className={event.image ? "" : "placeholder-img"}
          />
          <div className="image-overlay">
            <span className="badge category">
              {event.category || "No category"}
            </span>
            <span className={`badge status ${!event.status ? "missing" : ""}`}>
              <span className="dot"></span> {/* The dot inside the status container */}
              {event.status || "No status"}
            </span>
          </div>
        </div>

        {/* Actions Dropdown */}
        <div id="event-actions-container">
          <button
            type="button"
            data-type="dropdown"
            data-target={`#event-dropdown-${event.id}`}
            className="btn-action"
          >
            <i className="fa-solid fa-ellipsis"></i>
          </button>

          <div id={`event-dropdown-${event.id}`} className="dropdown">
            <div className="dropdown-body">
              <nav className="dropdown-actions">
                <button
                  data-type="modal"
                  data-target="#add-event-modal"
                  data-id={event.id}
                  data-name={event.name}
                  data-category={event.category}
                  data-status={event.status}
                  data-date={event.date}
                  data-location={event.location}
                  data-price={event.price}
                  className="dropdown-action"
                >
                  <i className="fa-solid fa-pen-to-square"></i>
                  <span>Add Event</span>
                </button>
              </nav>

              <div className="divider"></div>

              <nav className="dropdown-actions">
                <button
                  data-type="modal"
                  data-target="#edit-event-modal"
                  data-id={event.id}
                  data-name={event.name}
                  data-category={event.category}
                  data-status={event.status}
                  data-date={event.date}
                  data-location={event.location}
                  data-price={event.price}
                  className="dropdown-action"
                >
                  <i className="fa-solid fa-plus"></i>
                  <span>Edit Event</span>
                </button>
              </nav>

              <div className="divider"></div>

              <nav className="dropdown-actions">
                <button
                  data-type="modal"
                  data-target="#delete-event-modal"
                  data-id={event.id}
                  data-name={event.name}
                  className="dropdown-action"
                >
                  <i className="fa-solid fa-trash"></i>
                  <span>Delete Event</span>
                </button>
              </nav>
            </div>
          </div>
        </div>
      </div>

      {/* BODY: Date, title, location */}
      <div className="card-body">
        <p className="event-date-time">{event.date ?? "No date"}</p>
        <h4 className="event-title">{event.name ?? "Untitled Event"}</h4>
        <p className="event-location">
          <i className="fa-solid fa-location-dot"></i>
          {event.location || "No location"}
        </p>
      </div>

      {/* FOOTER: Progress and price */}
      <div className="card-footer">
        <div className="event-progress">
          <div className="progress-bar">
            <div className="progress" style={{ width: "65%" }}></div>
          </div>
          <span className="progress-label"><img src="/chart.svg" alt="chart"></img>65%</span>
        </div>
        <div className="event-price">
          {event.price ? `$${event.price}` : "No price"}
        </div>
      </div>
    </div>
  );
};

/* EventCard formatted to JSX from Razor by help of ChatGpt4o, code generated by ChatGpt 4o and updateded structure to match eventcard from figma */

export default EventCard;
